default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud config set project parkpal-384815
  
build:
  stage: build
  script:
    - gcloud builds submit --tag gcr.io/parkpal-384815

deploy:
  stage: deploy
  script:
    - gcloud run deploy monorepo --image gcr.io/parkpal-384815/monorepo --platform managed --region europe-west1-b --allow-unauthenticated
