services:

  locations:
    build: ./location_microservice
    ports:
      - "3002:3002"
    environment:
      - JWT_SECRET=pZnf1tK5NNWfgv6NlWpHVCk/+pFQxIzIdKec8JTn+GA=
      - PORT=3002
      - DB_URL=mongodb+srv://user:WsfePqVVojP4lgZk@locationservice.dqljyov.mongodb.net/ParkingLocations?retryWrites=true&w=majority

  notifications:
    build: ./notification-service
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=pZnf1tK5NNWfgv6NlWpHVCk/+pFQxIzIdKec8JTn+GA=
      - PORT=3001
  authentication:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb+srv://authservice:uB16msEdK3v6tvC7@authservicedatabase.pjqxc4j.mongodb.net/?retryWrites=true&w=majority
      - PORT=3000
      - JWT_SECRET=pZnf1tK5NNWfgv6NlWpHVCk/+pFQxIzIdKec8JTn+GA=

  frontend:
    build: ./frontend
    ports:
      - "25565:25565"
    environment:
      - REACT_APP_NOTIFICATION_SERVICE_ENDPOINT=http://localhost:3001
      - REACT_APP_AUTH_SERVICE_ENDPOINT=http://localhost:3000
      - REACT_APP_LOCATION_SERVICE_ENDPOINT=http://localhost:3002
      - PORT=25565

    depends_on:
      - authentication
      - notifications
